### ISSUE TITLE
Missing shapes in generated code using wasm-tools v1.226.0

### ISSUE THREAD

**Issue by alexcasalboni** [bytecodealliance/go-modules#297]
Everything worked well until a couple of days ago (with `wasm-tools@v1.225.0`).

With the latest wasm-tools, our generated code is missing some shapes.

Failing GitHub Action here: https://github.com/edgee-cloud/example-go-component/actions/runs/13455120736/job/37597335001?pr=7

How to reproduce:

```toml
# wit/deps.toml
edgee = "https://github.com/edgee-cloud/edgee-wit/archive/refs/tags/v0.5.0.tar.gz"
cli = "https://github.com/WebAssembly/wasi-cli/archive/refs/tags/v0.2.0.tar.gz"
```

```wit
// wit/world.wit
package edgee:native;

world data-collection {
  include wasi:cli/imports@0.2.0;
  export edgee:components/data-collection;
}
```

Generate with:

```bash
go run go.bytecodealliance.org/cmd/wit-bindgen-go generate -o internal/ ./wit
```

Check the file `internal/edgee/components/data-collection/abi.go` - there should be a type called `EdgeeRequestShape` but it's not there.
